### ISSUE TITLE
child_process error on Windows.

### ISSUE THREAD

**Issue by misak1** [HAASLEWER/unoconv2#1]
windows can it support ?

```
c:\Users\9104-100131\Desktop\unoconv_test>node index.js

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

**Comment by licongmu** [comment]
i also get this err

**Comment by suggy75** [comment]
Me too. Running node 5.1.0

**Comment by HAASLEWER** [comment]
Hi,

I forked this project a while ago as it seems the creator is no longer supporting it.  The new package includes the childprocess fix.

https://github.com/HAASLEWER/unoconv2
https://www.npmjs.com/package/unoconv2

I hope this helps.

**Comment by suggy75** [comment]
Hi,

Thanks for the response. This is the version I'm currently trying out. It's
on a windows machine, which I know are a bit funny about running terminal
commands in a child process. I'll try it on my mac at home tonight.

Cheers
Matt

**Comment by suggy75** [comment]
Get the same error on Mac also, different line number though.

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:874:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)

I'm running node v.4.2.0 on here.

**Comment by SHocker-Yu** [comment]
i get the same error,did you figure it out ?

**Comment by SHocker-Yu** [comment]
http://stackoverflow.com/questions/17516772/using-nodejss-spawn-causes-unknown-option-and-error-spawn-enoent-err#

I do this change:
child = childProcess.spawn(process.platform === "win32" ? "npm.cmd" : "npm", ['install']);
There is no error already,but the generate PDF document can't open successfully.

**Comment by andre0799** [comment]
same problem here

`Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:592:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3`

**Comment by DerekCL** [comment]
Same error as above

Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:1018:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by DJTouchette** [comment]
Anyone get around this?

**Comment by thisromantelecom** [comment]
```
events.js:180
      throw er; // Unhandled 'error' event
      ^

Error: spawn unoconv ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:270:12)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:77:11) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn unoconv',
  path: 'unoconv',
```

**Comment by looeee** [comment]
On threads related to this issue I've seen people reccoment to add `C:\Windows\System32` to you environment variables.

**Comment by georgemck** [comment]
For Windows 10, I resolved this with Windows Subsystem Linux (WSL).

According to unoconv distribution (http://dag.wiee.rs/home-made/unoconv/#download), there were no Windows versions available for installation. I installed the dependency "unoconv" in my Ubuntu file system and converted the DOCX to PDF there.

My final code was modified slightly to write the file to the hard disk: 

```
const fs = require('fs'), path = require('path'), unoconv = require('unoconv2');
unoconv.convert('test.docx', 'pdf', function (err, buffer) {
  fs.writeFileSync(path.resolve('', 'test.pdf'), buffer);
});
```

Here is a screenshot:
https://github.com/georgemck/unoconv-example/blob/master/screenshot.JPG
